
# Tamil Nadu Election Analysis (2021 vs 2026)
## AtliQ Media Resume Project Challenge

---

### Project Objective
This project analyzes how Tamil Nadu's political landscape changed between the 2021 and 2026 Assembly elections using constituency-level and regional-level election data.

### Key Areas of Analysis
- Regional Political Fragmentation
- Constituency-Level Volatility
- Vote Share Dynamics
- TVK's Statewide Emergence

### Tools & Technologies
- Python
- Pandas
- Plotly
- Power BI

---


# Notebook Structure

1. Data Loading & Understanding  
2. Data Cleaning & Validation  
3. Election Winner Analysis  
4. Regional Political Landscape  
5. Constituency Flip Analysis  
6. Vote Share Dynamics  
7. Key Insights & Conclusions  

---

**Domain**:

**Media**/ **Broadcasting**

## Problem Statement

**AtliQ Media** is producing a one-hour TV show on the 2026 Tamil Nadu Assembly election results. Unlike most channels covering the election with debates and political commentary, AtliQ wants the opposite - a clean, fact-based show grounded only in ECI data.


You have been hired as a data analyst to find the most interesting stories in the 2026 results, support each with a clear chart, and pitch them in a way that helps AtliQ plan the show. You are not asked to explain why any party won or lost, or to predict what will happen next.



In 2026, AI can do most of the analysis for you. The real skill being tested is storytelling: picking the right numbers, framing them so a regular viewer understands, and holding their attention without using complicated charts.

In [1]:
# import pandas

import pandas as pd

# import the three dataset provided in the challenge

constituency = pd.read_csv("/content/drive/MyDrive/Atliq Media/constituency_master.csv")

tn_2021_results = pd.read_csv("/content/drive/MyDrive/Atliq Media/tn_2021_results.csv")

tn_2026_results = pd.read_csv("/content/drive/MyDrive/Atliq Media/tn_2026_results.csv")

# Look at some data using head() dataframe
print("Constituency:\n", constituency.head(), "\n\n")

print("tn_2021_results:\n", tn_2021_results.head(), "\n\n")

print("tn_2026_results:\n", tn_2026_results.head())

Constituency:
    ac_number  constituency    district         region reserved
0          1  Gummidipundi  Tiruvallur  Chennai Metro      GEN
1          2       Ponneri  Tiruvallur  Chennai Metro       SC
2          3     Tiruttani  Tiruvallur  Chennai Metro      GEN
3          4   Thiruvallur  Tiruvallur  Chennai Metro      GEN
4          5   Poonamallee  Tiruvallur  Chennai Metro       SC


tn_2021_results:
    constituency  ac_number          candidate party   votes  turnout reserved  \
0  Gummidipundi          1   GOVINDARAJAN T.J   DMK  126452    78.08      GEN
1  Gummidipundi          1          PRAKASH M   PMK   75514    78.08      GEN
2  Gummidipundi          1               USHA   NTK   11701    78.08      GEN
3  Gummidipundi          1         DILLIY K.M  DMDK    2576    78.08      GEN
4  Gummidipundi          1  None Of The Above  NOTA    1783    78.08      GEN

          region
0  Chennai Metro
1  Chennai Metro
2  Chennai Metro
3  Chennai Metro
4  Chennai Metro


tn_2026_results:
     constituency  ac_number         candidate   party  votes  turnout  \
0  Gummidipoondi          1     S.VIJAYAKUMAR     TVK  94320      NaN
1  Gummidipoondi          1        SUDHAKAR.V  AIADMK  66375      NaN
2  Gummidipoondi          1  T.J.GOVINDARAJAN     DMK  62492      NaN
3  Gummidipoondi          1   R.SRIDAR. B.L.,     NTK   4756      NaN
4  Gummidipoondi          1              NOTA    NOTA    937      NaN

  reserved         region
0      GEN  Chennai Metro
1      GEN  Chennai Metro
2      GEN  Chennai Metro
3      GEN  Chennai Metro
4      GEN  Chennai Metro

### Data Dictionary

Column Description for tn_2021_results.csv and tn_2026_results.csv:
1. constituency: The name of the Assembly Constituency in Tamil Nadu.
2. ac_number: The official Election Commission AC number (1 to 234). Use this as the primary key when joining files.
3. candidate: The name of the candidate as recorded by the ECI.
4. party: Standardized party abbreviation (DMK, AIADMK, TVK, INC, BJP, PMK, VCK, NTK, CPI, CPI(M), IND, NOTA, etc.).
5. votes: Total votes received by the candidate in that constituency.
6. turnout: Constituency-level voter turnout percentage. This is the same value for every row in a given constituency.
7. reserved: Constituency reservation status. GEN = general / unreserved, SC = reserved for Scheduled Caste, ST = reserved for Scheduled Tribe.
                Tamil Nadu has 188 GEN, 44 SC, and 2 ST constituencies (same in both 2021 and 2026 — no delimitation change).
8. region: Editorial six-region grouping (Chennai Metro, North, Central, Kongu, Delta, South). This is NOT an official ECI classification — it is the grouping convention used in this challenge to enable regional analysis. See constituency_master.csv for the full mapping.



Column Description for constituency_master.csv:
1. ac_number: Official ECI AC number (1 to 234).
2. constituency: AC name.
3. district: Administrative district the constituency belongs to.
4. region: Six-region editorial grouping (Chennai Metro, North, Central, Kongu, Delta, South).
5. reserved: GEN, SC, or ST.

In [2]:
# Let's look at tables using dataframes.
# Let's know the the number of rows and columns in each tables.

print("Constituency:\n", constituency.shape, "\n\n")
print("tn_2021_results:\n", tn_2021_results.shape, "\n\n")
print("tn_2026_results):\n", tn_2026_results.shape)

Constituency:
 (234, 5)


tn_2021_results:
 (4232, 8)


tn_2026_results):
 (4257, 8)

In [3]:
# Let's know the column name of each tables.

print("Constituency\n",constituency.columns,"\n")
print("tn_2021_results\n",tn_2021_results.columns,"\n")
print("tn_2026_results\n",tn_2026_results.columns,"\n")

Constituency
 Index(['ac_number', 'constituency', 'district', 'region', 'reserved'], dtype='object')

tn_2021_results
 Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region'],
      dtype='object')

tn_2026_results
 Index(['constituency', 'ac_number', 'candidate', 'party', 'votes', 'turnout',
       'reserved', 'region'],
      dtype='object')

In [4]:
# Let's know the information of each tables.

print("Constituency:\n")
print(constituency.info(),"\n")
print("tn_2021_results:\n")
print(tn_2021_results.info(),"\n")
print("tn_2026_results:\n")
print(tn_2026_results.info())

Constituency:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ac_number     234 non-null    int64
 1   constituency  234 non-null    object
 2   district      234 non-null    object
 3   region        234 non-null    object
 4   reserved      234 non-null    object
dtypes: int64(1), object(4)
memory usage: 9.3+ KB
None

tn_2021_results:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4232 entries, 0 to 4231
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4232 non-null   object
 1   ac_number     4232 non-null   int64
 2   candidate     4232 non-null   object
 3   party         4232 non-null   object
 4   votes         4232 non-null   int64
 5   turnout       4232 non-null   float64
 6   reserved      4232 non-null   object
 7   region        4232 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 264.6+ KB
None

tn_2026_results:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4257 entries, 0 to 4256
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4257 non-null   object
 1   ac_number     4257 non-null   int64
 2   candidate     4257 non-null   object
 3   party         4257 non-null   object
 4   votes         4257 non-null   int64
 5   turnout       0 non-null      float64
 6   reserved      4257 non-null   object
 7   region        4257 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 266.2+ KB
None

In [5]:
# Check for duplicates

print("Constituency:\n", constituency.duplicated().sum(), "\n")
print("tn_2021_results:\n", tn_2021_results.duplicated().sum(), "\n")
print("tn_2026_results:\n", tn_2026_results.duplicated().sum())

Constituency:
 0

tn_2021_results:
 0

tn_2026_results:
 0

In [6]:
# Check for missing values

# Constituency
print("Constituency\n")
print(constituency.isnull().sum(),"\n")

# tn_2021_results
print("tn_2021_results\n")
print(tn_2021_results.isnull().sum(),"\n")

# tn_2026_result
print("tn_2026_results\n")
print(tn_2026_results.isnull().sum())

Constituency

ac_number       0
constituency    0
district        0
region          0
reserved        0
dtype: int64

tn_2021_results

constituency    0
ac_number       0
candidate       0
party           0
votes           0
turnout         0
reserved        0
region          0
dtype: int64

tn_2026_results

constituency       0
ac_number          0
candidate          0
party              0
votes              0
turnout         4257
reserved           0
region             0
dtype: int64

In [58]:
# Unique rows
tn_2021_results['ac_number'].nunique()

234

In [59]:
# Unique rows
tn_2026_results['ac_number'].nunique()

234

In [60]:
# Unique rows
constituency['ac_number'].nunique()

234

In [8]:
# Find index of candidate with maximum votes in each constituency

winner_index_2021 = tn_2021_results.groupby('ac_number')['votes'].idxmax()

# Create winners table

winners_2021 = tn_2021_results.loc[winner_index_2021]

# Display result

winners_2021.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
13,Ponneri,2,DURAI. CHANDRASEKAR,INC,94528,78.20,SC,Chennai Metro
24,Tiruttani,3,S.Chandran,DMK,120314,78.76,GEN,Chennai Metro
39,Thiruvallur,4,"RAAJENDRAN, V.G.",DMK,107709,77.20,GEN,Chennai Metro
51,Poonamallee,5,Krishnaswamy A,DMK,149578,72.99,SC,Chennai Metro

In [9]:
# Unique rows
winner_index_2021.index.nunique()

234

In [10]:
winner_index_2021.head()

ac_number
1     0
2    13
3    24
4    39
5    51
Name: votes, dtype: int64

In [62]:
winners_2021.shape

(234, 8)

In [11]:
# Find index of candidate with maximum votes in each constituency

winner_index_2026 = tn_2026_results.groupby('ac_number')['votes'].idxmax()

# Create winners table

winners_2026 = tn_2026_results.loc[winner_index_2026]

# Display result

winners_2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
16,Ponneri,2,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro
30,Tiruttani,3,G.HARI,AIADMK,89169,NaN,GEN,Chennai Metro
44,Thiruvallur,4,DR. T. ARUNKUMAR,TVK,92190,NaN,GEN,Chennai Metro
59,Poonamallee,5,PRAKASAM.R,TVK,161309,NaN,SC,Chennai Metro

In [12]:
# Rename columns
# This avoids confusion after merging.
winners_2021 = winners_2021.rename(columns={
    'candidate': 'winner_candidate_2021',
    'party': 'winner_party_2021',
    'votes': 'winner_votes_2021',
    'turnout': 'turnout_2021'
})

winners_2026 = winners_2026.rename(columns={
    'candidate': 'winner_candidate_2026',
    'party': 'winner_party_2026',
    'votes': 'winner_votes_2026',
    'turnout': 'turnout_2026'
})

In [63]:
winners_2021

,constituency,ac_number,winner_candidate_2021,winner_party_2021,winner_votes_2021,turnout_2021,reserved,region
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro
13,Ponneri,2,DURAI. CHANDRASEKAR,INC,94528,78.20,SC,Chennai Metro
24,Tiruttani,3,S.Chandran,DMK,120314,78.76,GEN,Chennai Metro
39,Thiruvallur,4,"RAAJENDRAN, V.G.",DMK,107709,77.20,GEN,Chennai Metro
51,Poonamallee,5,Krishnaswamy A,DMK,149578,72.99,SC,Chennai Metro
...,...,...,...,...,...,...,...,...
4159,Nagercoil,230,Gandhi M.R.,BJP,88804,67.06,GEN,South
4175,Colachel,231,Prince J.G.,INC,90681,67.27,GEN,South
4188,Padmanabhapuram,232,"Mano Thangaraj, T.",DMK,87744,70.08,GEN,South
4201,Vilavancode,233,VIJAYADHARANI S,INC,87473,66.83,GEN,South
4217,Killiyoor,234,RAJESH KUMAR S,INC,101541,65.87,GEN,South

In [64]:
winners_2026

,constituency,ac_number,winner_candidate_2026,winner_party_2026,winner_votes_2026,turnout_2026,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
16,Ponneri,2,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro
30,Tiruttani,3,G.HARI,AIADMK,89169,NaN,GEN,Chennai Metro
44,Thiruvallur,4,DR. T. ARUNKUMAR,TVK,92190,NaN,GEN,Chennai Metro
59,Poonamallee,5,PRAKASAM.R,TVK,161309,NaN,SC,Chennai Metro
...,...,...,...,...,...,...,...,...
4181,Nagercoil,230,AUSTIN,DMK,69880,NaN,GEN,South
4202,Colachal,231,THARAHAI CUTHBERT,INC,66207,NaN,GEN,South
4216,Padmanabhapuram,232,CHELLASWAMY. R,CPI(M),68938,NaN,GEN,South
4228,Vilavancode,233,PRAVEEN T.T,INC,70755,NaN,GEN,South
4243,Killiyoor,234,RAJESH KUMAR. S,INC,66434,NaN,GEN,South

In [13]:
# Merge both election years

# This is one of the MOST important tables in the project.

"""
Merge 2021 and 2026 winners tables using constituency (ac_number)
to create a constituency-level election comparison dataset.
This table will be used for flip analysis, regional shifts,
seat comparison, and other cross-year election insights.
"""

election_comparison = pd.merge(
    winners_2021,
    winners_2026,
    on='ac_number',
    suffixes=('_2021', '_2026')
)

election_comparison.head()

,constituency_2021,ac_number,winner_candidate_2021,winner_party_2021,winner_votes_2021,turnout_2021,reserved_2021,region_2021,constituency_2026,winner_candidate_2026,winner_party_2026,winner_votes_2026,turnout_2026,reserved_2026,region_2026
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro,Gummidipoondi,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
1,Ponneri,2,DURAI. CHANDRASEKAR,INC,94528,78.20,SC,Chennai Metro,Ponneri,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro
2,Tiruttani,3,S.Chandran,DMK,120314,78.76,GEN,Chennai Metro,Tiruttani,G.HARI,AIADMK,89169,NaN,GEN,Chennai Metro
3,Thiruvallur,4,"RAAJENDRAN, V.G.",DMK,107709,77.20,GEN,Chennai Metro,Thiruvallur,DR. T. ARUNKUMAR,TVK,92190,NaN,GEN,Chennai Metro
4,Poonamallee,5,Krishnaswamy A,DMK,149578,72.99,SC,Chennai Metro,Poonamallee,PRAKASAM.R,TVK,161309,NaN,SC,Chennai Metro

In [14]:
# create flip column
election_comparison['flipped'] = (
    election_comparison['winner_party_2021']
    != election_comparison['winner_party_2026']
)

A **flip** happens when the party that won a constituency in the previous election no longer wins it in the next election.

In [15]:
# Check number of flipped constituencies
election_comparison['flipped'].value_counts()

flipped
True     163
False     71
Name: count, dtype: int64

In [16]:
"""
Group the 2021 winners data by region and winning party
to calculate the number of seats won by each party
in each region during the 2021 Tamil Nadu Assembly election.
"""

region_2021 = (
    winners_2021
    .groupby(['region', 'winner_party_2021'])
    .size()
    .reset_index(name='seats_2021')
)

region_2021.head()

    region winner_party_2021  seats_2021
0  Central            AIADMK          15
1  Central               DMK          21
2  Central               INC           1
3  Central               PMK           3
4  Central               VCK           1

In [17]:
"""
Group the 2026 winners data by region and winning party
to calculate the number of seats won by each party
in each region during the 2021 Tamil Nadu Assembly election.
"""

region_2026 = (
    winners_2026
    .groupby(['region', 'winner_party_2026'])
    .size()
    .reset_index(name='seats_2026')
)

region_2026.head()

    region winner_party_2026  seats_2026
0  Central            AIADMK          15
1  Central              DMDK           1
2  Central               DMK           8
3  Central               PMK           3
4  Central               TVK          12

In [18]:
region_2021 = region_2021.rename(
    columns={'winner_party_2021': 'party'}
)

region_2026 = region_2026.rename(
    columns={'winner_party_2026': 'party'}
)

In [19]:
region_2021.head()

    region   party  seats_2021
0  Central  AIADMK          15
1  Central     DMK          21
2  Central     INC           1
3  Central     PMK           3
4  Central     VCK           1

In [65]:
region_2026.head()

    region   party  seats_2026
0  Central  AIADMK          15
1  Central    DMDK           1
2  Central     DMK           8
3  Central     PMK           3
4  Central     TVK          12

In [20]:
"""
Merge the 2021 and 2026 regional seat distribution tables
to compare how party-wise seat counts changed across regions
between the two elections.
"""

regional_shift = pd.merge(
    region_2021,
    region_2026,
    on=['region', 'party'],
    how='outer'
)

regional_shift.head()

    region   party  seats_2021  seats_2026
0  Central  AIADMK        15.0        15.0
1  Central    DMDK         NaN         1.0
2  Central     DMK        21.0         8.0
3  Central     INC         1.0         NaN
4  Central     PMK         3.0         3.0

In [21]:
# Fill NA values with 0
regional_shift = regional_shift.fillna(0)

In [22]:
"""
Calculate the change in seats won by each party in each region
between the 2021 and 2026 elections.
Positive values indicate seat gains, while negative values indicate seat losses.
"""

regional_shift['seat_change'] = (
    regional_shift['seats_2026']
    - regional_shift['seats_2021']
)

In [23]:
regional_shift.head()

    region   party  seats_2021  seats_2026  seat_change
0  Central  AIADMK        15.0        15.0          0.0
1  Central    DMDK         0.0         1.0          1.0
2  Central     DMK        21.0         8.0        -13.0
3  Central     INC         1.0         0.0         -1.0
4  Central     PMK         3.0         3.0          0.0

In [66]:
"""
Sort the regional seat distribution table by region and 2026 seat count
to make the comparison more organized and easier to interpret.
Within each region, parties with higher seat counts in 2026
will appear first.
"""

"""
This organized table helps identify which parties dominated,
gained, or lost seats across Tamil Nadu’s six regions
between the 2021 and 2026 elections.
"""

regional_shift = regional_shift.sort_values(
    by=['region', 'seats_2026'],
    ascending=[True, False]
)

regional_shift.head(20)

           region   party  seats_2021  seats_2026  seat_change
0         Central  AIADMK        15.0        15.0          0.0
5         Central     TVK         0.0        12.0         12.0
2         Central     DMK        21.0         8.0        -13.0
4         Central     PMK         3.0         3.0          0.0
6         Central     VCK         1.0         2.0          1.0
1         Central    DMDK         0.0         1.0          1.0
3         Central     INC         1.0         0.0         -1.0
10  Chennai Metro     TVK         0.0        29.0         29.0
8   Chennai Metro     DMK        29.0         2.0        -27.0
7   Chennai Metro  AIADMK         0.0         1.0          1.0
9   Chennai Metro     INC         3.0         0.0         -3.0
15          Delta     DMK        23.0        14.0         -9.0
18          Delta     TVK         0.0        10.0         10.0
11          Delta  AIADMK         4.0         4.0          0.0
12          Delta    AMMK         0.0         1.0          1.0
13          Delta     CPI         1.0         1.0          0.0
14          Delta  CPI(M)         2.0         1.0         -1.0
16          Delta     INC         2.0         1.0         -1.0
17          Delta    IUML         0.0         1.0          1.0
19          Delta     VCK         1.0         0.0         -1.0

In [26]:
"""
Sort the regional seat comparison table by seat change
in descending order to identify the largest seat gains
between the 2021 and 2026 elections.
"""

regional_shift.sort_values(
    by='seat_change',
    ascending=False
).head(15)

           region   party  seats_2021  seats_2026  seat_change
10  Chennai Metro     TVK         0.0        29.0         29.0
38          South     TVK         0.0        26.0         26.0
24          Kongu     TVK         0.0        16.0         16.0
31          North     TVK         0.0        15.0         15.0
5         Central     TVK         0.0        12.0         12.0
18          Delta     TVK         0.0        10.0         10.0
25          North  AIADMK        12.0        15.0          3.0
29          North    IUML         0.0         1.0          1.0
7   Chennai Metro  AIADMK         0.0         1.0          1.0
35          South  CPI(M)         0.0         1.0          1.0
12          Delta    AMMK         0.0         1.0          1.0
6         Central     VCK         1.0         2.0          1.0
1         Central    DMDK         0.0         1.0          1.0
17          Delta    IUML         0.0         1.0          1.0
4         Central     PMK         3.0         3.0          0.0

In [27]:
"""
Sort the regional seat comparison table by seat change
in ascending order to identify the largest seat losses
between the 2021 and 2026 elections.
"""

regional_shift.sort_values(
    by='seat_change'
).head(15)

           region   party  seats_2021  seats_2026  seat_change
8   Chennai Metro     DMK        29.0         2.0        -27.0
27          North     DMK        19.0         4.0        -15.0
2         Central     DMK        21.0         8.0        -13.0
20          Kongu  AIADMK        19.0         7.0        -12.0
33          South  AIADMK        16.0         5.0        -11.0
15          Delta     DMK        23.0        14.0         -9.0
36          South     DMK        31.0        22.0         -9.0
37          South     INC         9.0         4.0         -5.0
9   Chennai Metro     INC         3.0         0.0         -3.0
32          North     VCK         2.0         0.0         -2.0
23          Kongu     INC         2.0         0.0         -2.0
34          South     BJP         2.0         0.0         -2.0
16          Delta     INC         2.0         1.0         -1.0
19          Delta     VCK         1.0         0.0         -1.0
22          Kongu     DMK        10.0         9.0         -1.0

In [28]:
import plotly.express as px

fig = px.bar(
    regional_shift,
    x='region',
    y='seats_2026',
    color='party',
    barmode='group',
    hover_data=['seats_2021', 'seat_change'],
    title='Regional Seat Distribution - 2026'
)

fig.show()

In [29]:
# Export regional_shift as csv
regional_shift.to_csv(
    "regional_shift_analysis.csv",
    index=False
)

In [31]:
import plotly.express as px

fig = px.bar(
    regional_shift,
    x='region',
    y='seats_2026',
    color='party',
    barmode='group',
    hover_data=[
        'seats_2021',
        'seat_change'
    ],
    title='Regional Seat Distribution Comparison (2021 vs 2026)'
)

fig.show()

#Flip Story

In [32]:
# Filter constituencies where the winning party changed
# between the 2021 and 2026 elections

flipped_constituencies = election_comparison[
    election_comparison['winner_party_2021']
    != election_comparison['winner_party_2026']
]

flipped_constituencies.head()

,constituency_2021,ac_number,winner_candidate_2021,winner_party_2021,winner_votes_2021,turnout_2021,reserved_2021,region_2021,constituency_2026,winner_candidate_2026,winner_party_2026,winner_votes_2026,turnout_2026,reserved_2026,region_2026,flipped
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro,Gummidipoondi,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro,True
1,Ponneri,2,DURAI. CHANDRASEKAR,INC,94528,78.20,SC,Chennai Metro,Ponneri,DR.RAVI.M.S,TVK,110439,NaN,SC,Chennai Metro,True
2,Tiruttani,3,S.Chandran,DMK,120314,78.76,GEN,Chennai Metro,Tiruttani,G.HARI,AIADMK,89169,NaN,GEN,Chennai Metro,True
3,Thiruvallur,4,"RAAJENDRAN, V.G.",DMK,107709,77.20,GEN,Chennai Metro,Thiruvallur,DR. T. ARUNKUMAR,TVK,92190,NaN,GEN,Chennai Metro,True
4,Poonamallee,5,Krishnaswamy A,DMK,149578,72.99,SC,Chennai Metro,Poonamallee,PRAKASAM.R,TVK,161309,NaN,SC,Chennai Metro,True

In [33]:
# Count the total number of constituencies
# where the winning party changed

print(
    "Total Flipped Constituencies:",
    flipped_constituencies.shape[0]
)

Total Flipped Constituencies: 163

In [34]:
# Count how many constituencies shifted
# from one party to another

flip_flow = (
    flipped_constituencies
    .groupby([
        'winner_party_2021',
        'winner_party_2026'
    ])
    .size()
    .reset_index(name='flip_count')
)

flip_flow

   winner_party_2021 winner_party_2026  flip_count
0             AIADMK               DMK          15
1             AIADMK               INC           1
2             AIADMK              IUML           1
3             AIADMK               TVK          26
4             AIADMK               VCK           1
5                BJP               DMK           2
6                BJP               TVK           2
7             CPI(M)               TVK           1
8                DMK            AIADMK          22
9                DMK              AMMK           1
10               DMK            CPI(M)           1
11               DMK              IUML           1
12               DMK               PMK           3
13               DMK               TVK          65
14               INC               BJP           1
15               INC              DMDK           1
16               INC               DMK           1
17               INC               TVK          11
18               PMK            AIADMK           2
19               PMK               TVK           2
20               VCK            AIADMK           1
21               VCK               DMK           1
22               VCK               TVK           1

In [35]:
# Count flipped constituencies region-wise

region_flips = (
    flipped_constituencies
    .groupby('region_2021')
    .size()
    .reset_index(name='flip_count')
    .sort_values(
        by='flip_count',
        ascending=False
    )
)

region_flips

     region_2021  flip_count
5          South          38
1  Chennai Metro          30
4          North          27
3          Kongu          27
0        Central          26
2          Delta          15

In [36]:
flip_flow

   winner_party_2021 winner_party_2026  flip_count
0             AIADMK               DMK          15
1             AIADMK               INC           1
2             AIADMK              IUML           1
3             AIADMK               TVK          26
4             AIADMK               VCK           1
5                BJP               DMK           2
6                BJP               TVK           2
7             CPI(M)               TVK           1
8                DMK            AIADMK          22
9                DMK              AMMK           1
10               DMK            CPI(M)           1
11               DMK              IUML           1
12               DMK               PMK           3
13               DMK               TVK          65
14               INC               BJP           1
15               INC              DMDK           1
16               INC               DMK           1
17               INC               TVK          11
18               PMK            AIADMK           2
19               PMK               TVK           2
20               VCK            AIADMK           1
21               VCK               DMK           1
22               VCK               TVK           1

In [38]:
# Sort party-to-party constituency shifts
# by highest number of flipped constituencies

flip_flow = flip_flow.sort_values(
    by='flip_count',
    ascending=False
)

flip_flow.head(15)

   winner_party_2021 winner_party_2026  flip_count
13               DMK               TVK          65
3             AIADMK               TVK          26
8                DMK            AIADMK          22
0             AIADMK               DMK          15
17               INC               TVK          11
12               DMK               PMK           3
5                BJP               DMK           2
18               PMK            AIADMK           2
19               PMK               TVK           2
6                BJP               TVK           2
1             AIADMK               INC           1
4             AIADMK               VCK           1
2             AIADMK              IUML           1
10               DMK            CPI(M)           1
7             CPI(M)               TVK           1

In [39]:
import plotly.express as px

fig = px.bar(
    region_flips,
    x='region_2021',
    y='flip_count',
    color='flip_count',
    text='flip_count',
    title='Region-wise Flipped Constituencies'
)

fig.update_traces(textposition='outside')

fig.show()

In [ ]:
# Export constituency flip flow table
# for Power BI Sankey visualization

flip_flow.to_csv(
    "flip_flow_analysis.csv",
    index=False
)

In [ ]:
# Export region-wise flip analysis
# for dashboard and storytelling visuals

region_flips.to_csv(
    "region_flip_analysis.csv",
    index=False
)

#Vote Share Story

In [40]:
# Calculate total votes polled in each constituency for 2021

total_votes_2021 = (
    tn_2021_results
    .groupby('ac_number')['votes']
    .sum()
    .reset_index(name='total_votes_2021')
)

In [41]:
# Calculate total votes polled in each constituency for 2026

total_votes_2026 = (
    tn_2026_results
    .groupby('ac_number')['votes']
    .sum()
    .reset_index(name='total_votes_2026')
)

In [42]:
# Merge total constituency votes into both election datasets
# so that each candidate row also contains the total votes polled
# in that constituency for percentage and comparative analysis.

tn_2021_results = pd.merge(
    tn_2021_results,
    total_votes_2021,
    on='ac_number'
)

In [43]:
# Merge total constituency votes into both election datasets
# so that each candidate row also contains the total votes polled
# in that constituency for percentage and comparative analysis.

tn_2026_results = pd.merge(
    tn_2026_results,
    total_votes_2026,
    on='ac_number'
)

In [44]:
# Calculate candidate vote share percentage for 2021

tn_2021_results['vote_share_2021'] = (
    tn_2021_results['votes']
    / tn_2021_results['total_votes_2021']
) * 100

In [45]:
# Aggregate party vote share statewide - 2021
vote_share_2021 = (
    tn_2021_results
    .groupby('party')['votes']
    .sum()
    .reset_index(name='votes_2021')
)

In [46]:
# Aggregate party vote share statewide - 2026
vote_share_2026 = (
    tn_2026_results
    .groupby('party')['votes']
    .sum()
    .reset_index(name='votes_2026')
)

In [47]:
# Merge statewide totals
vote_share_comparison = pd.merge(
    vote_share_2021,
    vote_share_2026,
    on='party',
    how='outer'
).fillna(0)

In [48]:
# Calculate vote-share change
vote_share_comparison['vote_change'] = (
    vote_share_comparison['votes_2026']
    - vote_share_comparison['votes_2021']
)

In [49]:
# Sort parties by highest increase in votes
# between the 2021 and 2026 elections

vote_share_comparison.sort_values(
    by='vote_change',
    ascending=False
)


# This analysis identifies parties that gained
# the most votes between the 2021 and 2026 elections.

,party,votes_2021,votes_2026,vote_change
136,TVK,0.0,17226209.0,17226209.0
48,DMDK,200156.0,589500.0,389344.0
36,BJP,1213510.0,1467024.0,253514.0
18,All India Puratchi Thalaivar Makkal Munnettra ...,0.0,133473.0,133473.0
157,VCK,457763.0,540056.0,82293.0
...,...,...,...,...
110,PMK,1758774.0,1070745.0,-688029.0
97,NTK,3041974.0,1972537.0,-1069437.0
79,MNM,1210337.0,0.0,-1210337.0
0,AIADMK,15390974.0,10462146.0,-4928828.0
49,DMK,17430100.0,11929144.0,-5500956.0

In [50]:
# Sort parties by largest decline in votes
# between the 2021 and 2026 elections

vote_share_comparison.sort_values(
    by='vote_change'
)

# This analysis identifies parties that experienced
# the largest reduction in votes between the two elections.

,party,votes_2021,votes_2026,vote_change
49,DMK,17430100.0,11929144.0,-5500956.0
0,AIADMK,15390974.0,10462146.0,-4928828.0
79,MNM,1210337.0,0.0,-1210337.0
97,NTK,3041974.0,1972537.0,-1069437.0
110,PMK,1758774.0,1070745.0,-688029.0
...,...,...,...,...
157,VCK,457763.0,540056.0,82293.0
18,All India Puratchi Thalaivar Makkal Munnettra ...,0.0,133473.0,133473.0
36,BJP,1213510.0,1467024.0,253514.0
48,DMDK,200156.0,589500.0,389344.0
136,TVK,0.0,17226209.0,17226209.0

In [51]:
# Analyze TVK vote distribution across regions in 2026

tvk_region_votes = (
    tn_2026_results[
        tn_2026_results['party'] == 'TVK'
    ]
    .groupby('region')['votes']
    .sum()
    .reset_index(name='tvk_votes_2026')
    .sort_values(
        by='tvk_votes_2026',
        ascending=False
    )
)

tvk_region_votes

          region  tvk_votes_2026
5          South         3961386
1  Chennai Metro         3296372
0        Central         2764172
4          North         2676796
3          Kongu         2399218
2          Delta         2128265

In [52]:
# Create an interactive bar chart to visualize
# TVK's regional vote distribution in the 2026 election,
# helping identify regions where the party performed strongest.

import plotly.express as px

fig = px.bar(
    tvk_region_votes,
    x='region',
    y='tvk_votes_2026',
    color='tvk_votes_2026',
    text='tvk_votes_2026',
    title='TVK Vote Distribution Across Regions (2026)'
)

fig.update_traces(textposition='outside')

fig.show()

In [53]:
vote_share_comparison.sort_values(
    by='vote_change',
    ascending=False
)

,party,votes_2021,votes_2026,vote_change
136,TVK,0.0,17226209.0,17226209.0
48,DMDK,200156.0,589500.0,389344.0
36,BJP,1213510.0,1467024.0,253514.0
18,All India Puratchi Thalaivar Makkal Munnettra ...,0.0,133473.0,133473.0
157,VCK,457763.0,540056.0,82293.0
...,...,...,...,...
110,PMK,1758774.0,1070745.0,-688029.0
97,NTK,3041974.0,1972537.0,-1069437.0
79,MNM,1210337.0,0.0,-1210337.0
0,AIADMK,15390974.0,10462146.0,-4928828.0
49,DMK,17430100.0,11929144.0,-5500956.0

In [54]:
tvk_region_votes

          region  tvk_votes_2026
5          South         3961386
1  Chennai Metro         3296372
0        Central         2764172
4          North         2676796
3          Kongu         2399218
2          Delta         2128265

In [56]:
tvk_region_votes = (
    tn_2026_results[
        tn_2026_results['party'] == 'TVK'
    ]
    .groupby('region')['votes']
    .sum()
    .reset_index(name='tvk_votes_2026')
)

tvk_region_votes

          region  tvk_votes_2026
0        Central         2764172
1  Chennai Metro         3296372
2          Delta         2128265
3          Kongu         2399218
4          North         2676796
5          South         3961386

In [ ]:
# Export to csv
tvk_region_votes.to_csv(
    "tvk_region_votes.csv",
    index=False
)

In [ ]:
# Export to csv
vote_share_comparison.to_csv(
    "vote_share_comparison.csv",
    index=False
)


---

# Final Conclusions

### Key Findings
- Regional dominance became more fragmented in 2026.
- Several constituencies changed political control.
- TVK emerged as a statewide electoral force.
- Electoral competition intensified across Tamil Nadu.

### Project Outcome
This project demonstrates analytical storytelling using election data, combining Python-based analysis with Power BI dashboard design and presentation-driven insight communication.

---